preset: laravel

enabled:
  - strict
  - unalign_double_arrow
  - phpdoc_order
  - phpdoc_separation

disabled:
  - short_array_syntax
  - not_operator_with_successor_space

finder:
  exclude:
    - "public"
    - "resources"
    - "tests"
  name:
    - "*.php"

php:
  preset: laravel
  risky: true
  enabled:
    - strict
    - phpdoc_order
    - phpdoc_separation
  disabled:
    - align_double_arrow
  finder:
    exclude:
      - modules
      - node_modules
      - storage
      - vendor
      - resources
    name: "*.php"
    not-name: "*.blade.php"
js:
  tab-width: 4
  use-tabs: false
  print-width: 120
  double-quotes: false
  trailing-commas: es5
  semicolons: true
  arrow-parens: avoid
  bracket-spacing: true
  finder:
    exclude:
      - modules
      - node_modules
      - storage
      - vendor
    name:
      - "*.js"
      - "*.jsx"
    not-name:
      - "*.min.js"