dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4

env:
    - APP_ENV=testing

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'create database enso;'
  - mysql -uroot e "GRANT ALL PRIVILEGES ON enso.* TO root@127.0.0.1 IDENTIFIED BY 'password'"

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan config:cache --env=testing

script: vendor/bin/phpunit

after_success:
  - curl -s $DEPLOY_WEBHOOK

sudo: required
