script:
  - phpunit

after_success:
  - chmod +x ./.deploy.sh; ./.deploy.sh

language: php

php:
  - 7.2

before_script:
  - echo 'max_execution_time=500' > myconfig.ini
  - phpenv config-add myconfig.ini
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate


before_install:
  - mysql -e 'create database enso;'

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required