version: '3'

services:
  php:
    build: ./docker
    container_name: enso
    ports:
      - 8000:80
    volumes:
      - ./docker/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www/html
    environment:
      DB_HOST: mysqldb
      REDIS_HOST: redis
    depends_on:
      - mysqldb
      - redis
    networks:
      - enso

  mysqldb:
    image: mysql:8
    container_name: enso-${DB_CONNECTION}
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    networks:
      - enso

  redis:
    image: redis:latest
    networks:
      - enso

#  myadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    container_name: enso-phpmyadmin
#    ports:
#      - 8081:80
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=enso-${DB_CONNECTION}
#    restart: always
#    depends_on:
#      - mysqldb

networks:
  enso:
