version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/dev/app/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - postgres-testing
      - redis
      - mailhog
    hostname: api
    ports:
      - "8000:8000"
    networks:
      - api
      - gateway
    restart: unless-stopped

  queue:
    build:
      context: ./
      dockerfile: ./.docker/dev/queue/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    networks:
      - api

  schedule:
    build:
      context: ./
      dockerfile: ./.docker/dev/schedule/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    networks:
      - api

  postgres:
    build:
      context: ./
      dockerfile: ./.docker/dev/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./.docker/dev/postgres/dumps/:/tmp
    ports:
      - "5432:5432"
    networks:
      - api

  postgres-testing:
    build:
      context: ./
      dockerfile: ./.docker/dev/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - api

  redis:
    build:
      context: ./
      dockerfile: ./.docker/dev/redis/Dockerfile
    # TODO: Add one more volume for configuration (disable background saves)
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - api

  mailhog:
    build:
      context: ./
      dockerfile: ./.docker/dev/mailhog/Dockerfile
    ports:
      - "8025:8025"
    networks:
      - api

volumes:
  postgres:
    driver: local

  redis:
    driver: local

networks:
  api:
    name: api

  gateway:
    name: gateway
    external: true
