# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
      - name: 'install & build'
        run: |
          cd client
          yarn install
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: |
            public
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v4  
      - uses: borales/actions-yarn@v2.0.0
      - name: 'install & build'
        run: |
          ls
          sudo composer self-update
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
